name: turbo-turtle
services:
    db:
        image: postgres:17-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 2s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7-alpine
        restart: unless-stopped
        environment:
            - REDIS_USERNAME=${REDIS_USER}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        ports:
            - "6379:6379"
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 2s
            timeout: 5s
volumes:
    postgres_turbo_turtle_data:
